name: Format
on:
  pull_request:
  merge_group:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  format:
    uses: mozilla/actions/.github/workflows/rustfmt.yml@264c6b750df669adb58286a26c5d0e04e839e06b # v2.0.8

  toml:
    name: "Check TOML"
    timeout-minutes: 10
    runs-on: ubuntu-24.04
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - run: |
          npm ci --ignore-scripts
          npm exec tombi -- lint --offline
          npm exec tombi -- format --check --offline
