name: Machete
on:
  workflow_dispatch:
  pull_request:
  merge_group:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  machete:
    uses: mozilla/actions/.github/workflows/machete.yml@cd1f0dcf30d92e633a0a89c10a330542deed6f24 # v2.0.1
