name: Release
on: # zizmor: ignore[concurrency-limits] - release events are inherently serialised
  release:
    types: [published]

permissions: {}

jobs:
  release:
    name: Update major version tag
    uses: mozilla/actions/.github/workflows/release.yml@32d84c77ea1bb513afbd253f94f67ae138b7d8be # v2.0.10
    permissions:
      contents: write # Required to update the major version tag
    with:
      tag: ${{ github.event.release.tag_name }}
